import * as cornerstoneTools from "@cornerstonejs/tools";
import * as cornerstone from "@cornerstonejs/core";
import type { Types } from "@cornerstonejs/core";
import {
  EventTypes,
  ToolHandle,
  TextBoxHandle,
  PublicToolProps,
  ToolProps,
  SVGDrawingHelper,
  Annotation
} from "@cornerstonejs/tools/dist/esm/types";
import { annotation } from "@cornerstonejs/tools";
import { StyleSpecifier } from "./customLengthTool";
import {
  IEnabledElement,
  Point2,
  Point3
} from "@cornerstonejs/core/dist/esm/types";
const {
  getAnnotations,
  addAnnotation,
  removeAnnotation,
  triggerAnnotationCompleted,
  triggerAnnotationModified
} = annotation.state;
const { isAnnotationVisible } = annotation.visibility;
const { isAnnotationLocked } = annotation.locking;
const AnnotationTool = cornerstoneTools.AnnotationTool;
const getEnabledElement = cornerstone.getEnabledElement;
const getEnabledElementByViewportId = cornerstone.getEnabledElementByViewportId;
const drawLineSvg = cornerstoneTools.drawing.drawLine;
const drawPathSvg = cornerstoneTools.drawing.drawPath;
const enums = cornerstoneTools.Enums;
const Events = enums.Events;
const ChangeTypes = enums.ChangeTypes;
const lineSegment = cornerstoneTools.utilities.math.lineSegment;
const angleBetweenLines =
  cornerstoneTools.utilities.math.angle.angleBetweenLines;

const throttle = cornerstoneTools.utilities.throttle;

const drawHandlesSvg = cornerstoneTools.drawing.drawHandles;
const drawLinkedTextBoxSvg = cornerstoneTools.drawing.drawLinkedTextBox;

const state = cornerstoneTools.store.state;
const getViewportIdsWithToolToRender =
  cornerstoneTools.utilities.viewportFilters.getViewportIdsWithToolToRender;

const triggerAnnotationRenderForViewportIds =
  cornerstoneTools.utilities.triggerAnnotationRenderForViewportIds;
const resetElementCursor =
  cornerstoneTools.cursors.elementCursor.resetElementCursor;
const hideElementCursor =
  cornerstoneTools.cursors.elementCursor.hideElementCursor;
const { transformWorldToIndex } = cornerstone.utilities;
interface AngleAnnotation extends Annotation {
  data: {
    handles: {
      points: Types.Point3[];
      activeHandleIndex: number | null;
      textBox: {
        hasMoved: boolean;
        worldPosition: Types.Point3;
        worldBoundingBox: {
          topLeft: Types.Point3;
          topRight: Types.Point3;
          bottomLeft: Types.Point3;
          bottomRight: Types.Point3;
        };
      };
    };
    label: string;
    cachedStats: {
      [targetId: string]: {
        angle: number;
      };
    };
  };
}
class CustomAngleTool extends AnnotationTool {
  static toolName = "CustomAngle";

  angleStartedNotYetCompleted: boolean = false;
  _throttledCalculateCachedStats: Function;
  editData: {
    annotation: Annotation;
    viewportIdsToRender: string[];
    handleIndex?: number;
    movingTextBox?: boolean;
    newAnnotation?: boolean;
    hasMoved?: boolean;
  } | null = null;
  isDrawing: boolean = false;
  isHandleOutsideImage: boolean = false;
  public isMoving: boolean = false;
  public isResizing: boolean = false;
  constructor(
    toolProps: PublicToolProps = {},
    defaultToolProps: ToolProps = {
      supportedInteractionTypes: ["Mouse", "Touch"],
      configuration: {
        shadow: true,
        showAngleArc: false,
        arcOffset: 5, // Calculate radius as 1/5 of the minimum distance from center to lines
        preventHandleOutsideImage: false,
        getTextLines: defaultGetTextLines
      }
    }
  ) {
    super(toolProps, defaultToolProps);

    this._throttledCalculateCachedStats = throttle(
      this._calculateCachedStats,
      100,
      { trailing: true }
    );
  }

  static hydrate = (
    viewportId: string,
    points: Types.Point3[],
    options?: {
      annotationUID?: string;
      toolInstance?: CustomAngleTool;
      referencedImageId?: string;
      viewplaneNormal?: Types.Point3;
      viewUp?: Types.Point3;
    }
  ): AngleAnnotation | undefined => {
    const enabledElement = getEnabledElementByViewportId(viewportId);
    if (!enabledElement) {
      return;
    }
    const {
      FrameOfReferenceUID,
      referencedImageId,
      viewPlaneNormal,
      instance,
      viewport
    } = this.hydrateBase<CustomAngleTool>(
      CustomAngleTool,
      enabledElement,
      points,
      options
    );

    // Exclude toolInstance from the options passed into the metadata
    const { toolInstance, ...serializableOptions } = options || {};

    const annotation = {
      annotationUID: options?.annotationUID || cornerstone.utilities.uuidv4(),
      data: {
        handles: {
          points
        }
      },
      highlighted: false,
      autoGenerated: false,
      invalidated: false,
      isLocked: false,
      isVisible: true,
      metadata: {
        toolName: instance.getToolName(),
        viewPlaneNormal,
        FrameOfReferenceUID,
        referencedImageId,
        ...serializableOptions
      }
    };
    addAnnotation(annotation, viewport.element);

    triggerAnnotationRenderForViewportIds([viewport.id]);
  };

  /**
   * Based on the current position of the mouse and the current imageId to create
   * a Length Annotation and stores it in the annotationManager
   *
   * @param evt -  EventTypes.InteractionEventType
   * @returns The annotation object.
   *
   */
  addNewAnnotation = (evt: EventTypes.InteractionEventType): any => {
    if (this.angleStartedNotYetCompleted) {
      return;
    }

    this.angleStartedNotYetCompleted = true;
    const eventDetail = evt.detail;
    const { currentPoints, element } = eventDetail;

    const worldPos = currentPoints.world;
    const enabledElement = getEnabledElement(element);
    const { viewport, renderingEngine } = enabledElement!;

    hideElementCursor(element);
    this.isDrawing = true;

    const camera = viewport.getCamera();
    const { viewPlaneNormal, viewUp } = camera;

    const referencedImageId = this.getReferencedImageId(
      viewport,
      worldPos,
      viewPlaneNormal!,
      viewUp
    );

    const FrameOfReferenceUID = viewport.getFrameOfReferenceUID();

    const annotation = {
      highlighted: true,
      invalidated: true,
      metadata: {
        toolName: this.getToolName(),
        viewPlaneNormal: <Types.Point3>[...viewPlaneNormal!],
        viewUp: <Types.Point3>[...viewUp!],
        FrameOfReferenceUID,
        referencedImageId,
        ...viewport.getViewReference({ points: [worldPos] })
      },
      data: {
        handles: {
          points: [<Types.Point3>[...worldPos], <Types.Point3>[...worldPos]],
          activeHandleIndex: null,
          textBox: {
            hasMoved: false,
            worldPosition: <Types.Point3>[0, 0, 0],
            worldBoundingBox: {
              topLeft: <Types.Point3>[0, 0, 0],
              topRight: <Types.Point3>[0, 0, 0],
              bottomLeft: <Types.Point3>[0, 0, 0],
              bottomRight: <Types.Point3>[0, 0, 0]
            }
          }
        },
        label: "",
        cachedStats: {}
      }
    };

    addAnnotation(annotation, element);

    const viewportIdsToRender = getViewportIdsWithToolToRender(
      element,
      this.getToolName()
    );

    this.editData = {
      annotation,
      viewportIdsToRender,
      handleIndex: 1,
      movingTextBox: false,
      newAnnotation: true,
      hasMoved: false
    };
    this._activateDraw(element);

    evt.preventDefault();

    triggerAnnotationRenderForViewportIds(viewportIdsToRender);

    return annotation;
  };
  _getViewportsInfo = () => {
    const viewports = cornerstoneTools.ToolGroupManager.getToolGroup(
      this.toolGroupId
    )?.viewportsInfo;
    return viewports;
  };
  onSetToolEnabled() {
    const elementIds = this._getViewportsInfo()?.map(
      viewport => viewport.viewportId
    );

    elementIds?.forEach(id => {
      const element = document.getElementById(id);
      if (!element) return;

      element.removeEventListener(
        Events.MOUSE_MOVE,
        this._mouseMoveCallback as EventListener
      );
      element.removeEventListener(
        Events.MOUSE_DRAG,
        this._mouseMoveCallback as EventListener
      );
    });
  }
  onSetToolActive() {
    const elementIds = this._getViewportsInfo()?.map(
      viewport => viewport.viewportId
    );

    elementIds?.forEach(id => {
      const element = document.getElementById(id);
      if (!element) return;

      element.addEventListener(
        Events.MOUSE_MOVE,
        this._mouseMoveCallback as EventListener
      );
      element.addEventListener(
        Events.MOUSE_DRAG,
        this._mouseMoveCallback as EventListener
      );
    });
  }

  _mouseMoveCallback = (evt: EventTypes.InteractionEventType): void => {
    if (evt.detail.currentPoints && evt.detail.element) {
      const coords = evt.detail.currentPoints.canvas;
      const element = evt.detail.element;

      const currentState = this.getCurrentOperationState();

      const nearHandle = this.isNearHandle(element, coords);
      const nearMeas = this.isNearMeasurement(element, coords);
      this.setCursor(currentState, element, nearHandle, nearMeas);
    }
  };
  isNearHandle = (element: HTMLDivElement, coords: Types.Point2): boolean => {
    const annotations = getAnnotations(this.getToolName(), element);
    if (!annotations?.length) return false;

    const enabledElement = getEnabledElement(element);
    const { viewport } = enabledElement!;

    for (const annotation of annotations) {
      const lengthAnnotation = annotation as AngleAnnotation;

      if (
        !isAnnotationVisible(lengthAnnotation.annotationUID!) ||
        isAnnotationLocked(lengthAnnotation.annotationUID!)
      ) {
        continue;
      }

      const { data } = lengthAnnotation;
      const points = data.handles.points;

      for (let i = 0; i < points.length; i++) {
        const canvasPoint = viewport.worldToCanvas(points[i]);
        const distance = Math.sqrt(
          Math.pow(canvasPoint[0] - coords[0], 2) +
            Math.pow(canvasPoint[1] - coords[1], 2)
        );

        if (distance <= 6) {
          return true;
        }
      }
    }

    return false;
  };
  isNearMeasurement = (
    element: HTMLDivElement,
    coords: Types.Point2
  ): boolean => {
    const annotations = getAnnotations(this.getToolName(), element);
    if (!annotations?.length) return false;

    for (const annotation of annotations) {
      const lengthAnnotation = annotation as AngleAnnotation;

      if (
        !isAnnotationVisible(lengthAnnotation.annotationUID!) ||
        isAnnotationLocked(lengthAnnotation.annotationUID!)
      ) {
        continue;
      }

      if (this.isPointNearTool(element, lengthAnnotation, coords, 6)) {
        return true;
      }
    }

    return false;
  };
  getCurrentOperationState(): "READY" | "DRAWING" | "MODIFYING" | "MOVING" {
    if (this.isDrawing) return "DRAWING";
    if (this.isResizing) return "MODIFYING";
    if (this.isMoving) return "MOVING";
    return "READY";
  }

  setCursor(
    state: "READY" | "DRAWING" | "MODIFYING" | "MOVING",
    element: HTMLDivElement,
    nearHandle: boolean,
    nearMeas: boolean
  ) {
    let cursor: any;
    switch (state) {
      case "READY":
        cursor = this.toolName;
        if (nearMeas) cursor = "move";
        if (nearHandle) cursor = "resize";
        break;

      case "DRAWING":
        cursor = this.toolName;
        break;

      case "MODIFYING":
        cursor = "resize";
        break;

      case "MOVING":
        cursor = "move";
        break;
    }
    cornerstoneTools.cursors.setCursorForElement(element, cursor);
  }
  /**
   * It returns if the canvas point is near the provided length annotation in the provided
   * element or not. A proximity is passed to the function to determine the
   * proximity of the point to the annotation in number of pixels.
   *
   * @param element - HTML Element
   * @param annotation - Annotation
   * @param canvasCoords - Canvas coordinates
   * @param proximity - Proximity to tool to consider
   * @returns Boolean, whether the canvas point is near tool
   */
  isPointNearTool = (
    element: HTMLDivElement,
    annotation: AngleAnnotation,
    canvasCoords: Types.Point2,
    proximity: number
  ): boolean => {
    const enabledElement = getEnabledElement(element);
    const { viewport } = enabledElement!;
    const { data } = annotation;
    const [point1, point2, point3] = data.handles.points;
    const canvasPoint1 = viewport.worldToCanvas(point1);
    const canvasPoint2 = viewport.worldToCanvas(point2);

    const line1 = {
      start: {
        x: canvasPoint1[0],
        y: canvasPoint1[1]
      },
      end: {
        x: canvasPoint2[0],
        y: canvasPoint2[1]
      }
    };

    const distanceToPoint = lineSegment.distanceToPoint(
      [line1.start.x, line1.start.y],
      [line1.end.x, line1.end.y],
      [canvasCoords[0], canvasCoords[1]]
    );

    if (distanceToPoint <= proximity) {
      return true;
    }
    if (!point3) {
      return false;
    }

    const canvasPoint3 = viewport.worldToCanvas(point3);

    const line2 = {
      start: {
        x: canvasPoint2[0],
        y: canvasPoint2[1]
      },
      end: {
        x: canvasPoint3[0],
        y: canvasPoint3[1]
      }
    };

    const distanceToPoint2 = lineSegment.distanceToPoint(
      [line2.start.x, line2.start.y],
      [line2.end.x, line2.end.y],
      [canvasCoords[0], canvasCoords[1]]
    );

    if (distanceToPoint2 <= proximity) {
      return true;
    }

    return false;
  };

  toolSelectedCallback = (
    evt: EventTypes.InteractionEventType,
    annotation: AngleAnnotation
  ): void => {
    const eventDetail = evt.detail;
    const { element } = eventDetail;

    annotation.highlighted = true;

    const viewportIdsToRender = getViewportIdsWithToolToRender(
      element,
      this.getToolName()
    );

    this.editData = {
      annotation,
      viewportIdsToRender,
      movingTextBox: false
    };
    this.isMoving = true;
    this._activateModify(element);

    hideElementCursor(element);

    const enabledElement = getEnabledElement(element);
    const { renderingEngine } = enabledElement!;

    triggerAnnotationRenderForViewportIds(viewportIdsToRender);

    evt.preventDefault();
  };

  handleSelectedCallback(
    evt: EventTypes.InteractionEventType,
    annotation: AngleAnnotation,
    handle: ToolHandle
  ): void {
    const eventDetail = evt.detail;
    const { element } = eventDetail;
    const { data } = annotation;

    annotation.highlighted = true;

    let movingTextBox = false;
    let handleIndex;

    if ((handle as TextBoxHandle).worldPosition) {
      movingTextBox = true;
    } else {
      handleIndex = data.handles.points.findIndex((p: Point3) => p === handle);
    }

    // Find viewports to render on drag.
    const viewportIdsToRender = getViewportIdsWithToolToRender(
      element,
      this.getToolName()
    );

    this.editData = {
      annotation,
      viewportIdsToRender,
      handleIndex,
      movingTextBox
    };
    this.isResizing = true;
    this._activateModify(element);

    hideElementCursor(element);

    const enabledElement = getEnabledElement(element);
    const { renderingEngine } = enabledElement!;

    triggerAnnotationRenderForViewportIds(viewportIdsToRender);

    evt.preventDefault();
  }

  _endCallback = (evt: EventTypes.InteractionEventType): void => {
    const eventDetail = evt.detail;
    const { element } = eventDetail;

    const { annotation, viewportIdsToRender, newAnnotation, hasMoved } =
      this.editData!;

    const { data } = annotation;
    if (newAnnotation && !hasMoved) {
      // when user starts the drawing by click, and moving the mouse, instead
      // of click and drag
      return;
    }

    // If preventing new measurement means we are in the middle of an existing measurement
    // we shouldn't deactivate modify or draw
    if (
      this.angleStartedNotYetCompleted &&
      data.handles!.points!.length === 2
    ) {
      // adds the last point to the measurement
      this.editData!.handleIndex = 2;
      return;
    }

    this.angleStartedNotYetCompleted = false;
    data.handles!.activeHandleIndex = null;

    this._deactivateModify(element);
    this._deactivateDraw(element);
    resetElementCursor(element);

    const enabledElement = getEnabledElement(element);
    const { renderingEngine } = enabledElement!;

    if (
      this.isHandleOutsideImage &&
      this.configuration.preventHandleOutsideImage
    ) {
      removeAnnotation(annotation.annotationUID!);
    }

    triggerAnnotationRenderForViewportIds(viewportIdsToRender);
    this.doneEditMemo();

    if (newAnnotation) {
      triggerAnnotationCompleted(annotation);
    }

    this.editData = null;
    this.isDrawing = false;
    this.isMoving = false;
    this.isResizing = false;
  };

  private _getConstrainedDeltaForAnnotation = (
    newPositions: number[][],
    viewport: any,
    data: any
  ): number[] => {
    const image = this.getTargetImageData(this.getTargetId(viewport)!);
    if (!image) {
      const points = data.handles!.points;
      return newPositions.length > 0
        ? [
            newPositions[0][0] - points![0][0],
            newPositions[0][1] - points![0][1],
            newPositions[0][2] - points![0][2]
          ]
        : [0, 0, 0];
    }

    const { imageData, dimensions } = image;
    const points = data.handles!.points;
    const requestedDelta =
      newPositions.length > 0
        ? [
            newPositions[0][0] - points![0][0],
            newPositions[0][1] - points![0][1],
            newPositions[0][2] - points![0][2]
          ]
        : [0, 0, 0];

    let constrainedDelta = [...requestedDelta];

    for (let i = 0; i < newPositions.length; i++) {
      const currentWorldPos = points![i];
      const newWorldPos = newPositions[i] as Point3;
      const newIndexPos = transformWorldToIndex(imageData, newWorldPos);

      // Constrain the new index position to image bounds
      const constrainedIndexPos: Types.Point3 = [
        Math.max(0, Math.min(dimensions[0] - 1, newIndexPos[0])),
        Math.max(0, Math.min(dimensions[1] - 1, newIndexPos[1])),
        Math.max(0, Math.min(dimensions[2] - 1, newIndexPos[2]))
      ];

      const constrainedWorldPos = cornerstone.utilities.transformIndexToWorld(
        imageData,
        constrainedIndexPos
      );

      // Calculate the actual allowed delta for this point
      const actualDelta = [
        constrainedWorldPos[0] - currentWorldPos[0],
        constrainedWorldPos[1] - currentWorldPos[1],
        constrainedWorldPos[2] - currentWorldPos[2]
      ];

      // Use the most restrictive delta across all points
      for (let axis = 0; axis < 3; axis++) {
        if (Math.abs(actualDelta[axis]) < Math.abs(constrainedDelta[axis])) {
          constrainedDelta[axis] = actualDelta[axis];
        }
      }
    }

    return constrainedDelta;
  };

  private _constrainPointToImageBounds = (
    worldPos: Types.Point3,
    viewport: any
  ): Types.Point3 => {
    const image = this.getTargetImageData(this.getTargetId(viewport)!);
    if (!image) {
      return worldPos;
    }

    const { imageData, dimensions } = image;
    const indexPos = transformWorldToIndex(imageData, worldPos);

    // Constrain to image bounds
    const constrainedIndex: Types.Point3 = [
      Math.max(0, Math.min(dimensions[0] - 1, indexPos[0])),
      Math.max(0, Math.min(dimensions[1] - 1, indexPos[1])),
      Math.max(0, Math.min(dimensions[2] - 1, indexPos[2]))
    ];

    // Convert back to world coordinates
    const constrainedWorld = cornerstone.utilities.transformIndexToWorld(
      imageData,
      constrainedIndex
    );

    return constrainedWorld;
  };

  // Replace the existing _dragCallback method with this modified version
  _dragCallback = (evt: EventTypes.InteractionEventType): void => {
    this.isDrawing = !this.isResizing && !this.isMoving ? true : false;

    const eventDetail = evt.detail;
    const { element } = eventDetail;

    const {
      annotation,
      viewportIdsToRender,
      handleIndex,
      movingTextBox,
      newAnnotation
    } = this.editData!;
    const { data } = annotation;

    const enabledElement = getEnabledElement(element);
    const { viewport } = enabledElement!;

    this.createMemo(element, annotation, { newAnnotation });

    if (movingTextBox) {
      // Drag mode - moving text box
      const { deltaPoints } = eventDetail as EventTypes.MouseDragEventDetail;
      const worldPosDelta = deltaPoints.world;

      const { textBox } = data.handles!;
      const { worldPosition } = textBox!;

      const newTextBoxPosition: Types.Point3 = [
        worldPosition![0] + worldPosDelta[0],
        worldPosition![1] + worldPosDelta[1],
        worldPosition![2] + worldPosDelta[2]
      ];

      // Constrain text box position to image bounds
      const constrainedTextBoxPosition = this._constrainPointToImageBounds(
        newTextBoxPosition,
        viewport
      );

      worldPosition![0] = constrainedTextBoxPosition[0];
      worldPosition![1] = constrainedTextBoxPosition[1];
      worldPosition![2] = constrainedTextBoxPosition[2];

      textBox!.hasMoved = true;
    } else if (handleIndex === undefined) {
      // Drag mode - moving entire annotation
      const { deltaPoints } = eventDetail as EventTypes.MouseDragEventDetail;
      const worldPosDelta = deltaPoints.world;

      const points = data.handles!.points;
      const newPositions = points!.map(point => [
        point[0] + worldPosDelta[0],
        point[1] + worldPosDelta[1],
        point[2] + worldPosDelta[2]
      ]);

      // Get constrained delta
      const constrainedDelta = this._getConstrainedDeltaForAnnotation(
        newPositions,
        viewport,
        data
      );

      // Apply constrained delta to all points
      points!.forEach(point => {
        point[0] += constrainedDelta[0];
        point[1] += constrainedDelta[1];
        point[2] += constrainedDelta[2];
      });

      annotation.invalidated = true;
    } else {
      // Move mode - moving individual handle
      const { currentPoints } = eventDetail;
      const worldPos = currentPoints.world;

      // Constrain the new handle position to image bounds
      const constrainedWorldPos = this._constrainPointToImageBounds(
        worldPos,
        viewport
      );

      data.handles!.points![handleIndex] = [...constrainedWorldPos];
      annotation.invalidated = true;
    }

    this.editData!.hasMoved = true;

    const { renderingEngine } = enabledElement!;

    triggerAnnotationRenderForViewportIds(viewportIdsToRender);

    if (annotation.invalidated) {
      triggerAnnotationModified(
        annotation,
        element,
        ChangeTypes.HandlesUpdated
      );
    }
  };

  cancel = (element: HTMLDivElement) => {
    // If it is mid-draw or mid-modify
    if (this.isDrawing) {
      this.isDrawing = false;
      this._deactivateDraw(element);
      this._deactivateModify(element);
      resetElementCursor(element);

      const { annotation, viewportIdsToRender, newAnnotation } = this.editData!;
      const { data } = annotation;

      annotation.highlighted = false;
      data.handles!.activeHandleIndex = null;

      triggerAnnotationRenderForViewportIds(viewportIdsToRender);

      if (newAnnotation) {
        triggerAnnotationCompleted(annotation);
      }

      this.editData = null;
      this.angleStartedNotYetCompleted = false;
      return annotation.annotationUID;
    }
  };

  _activateModify = (element: HTMLDivElement) => {
    state.isInteractingWithTool = true;

    element.addEventListener(
      Events.MOUSE_UP,
      this._endCallback as EventListener
    );
    element.addEventListener(
      Events.MOUSE_DRAG,
      this._dragCallback as EventListener
    );
    element.addEventListener(
      Events.MOUSE_CLICK,
      this._endCallback as EventListener
    );

    element.addEventListener(
      Events.TOUCH_TAP,
      this._endCallback as EventListener
    );
    element.addEventListener(
      Events.TOUCH_END,
      this._endCallback as EventListener
    );
    element.addEventListener(
      Events.TOUCH_DRAG,
      this._dragCallback as EventListener
    );
  };

  _deactivateModify = (element: HTMLDivElement) => {
    state.isInteractingWithTool = false;

    element.removeEventListener(
      Events.MOUSE_UP,
      this._endCallback as EventListener
    );
    element.removeEventListener(
      Events.MOUSE_DRAG,
      this._dragCallback as EventListener
    );
    element.removeEventListener(
      Events.MOUSE_CLICK,
      this._endCallback as EventListener
    );
    element.removeEventListener(
      Events.TOUCH_TAP,
      this._endCallback as EventListener
    );
    element.removeEventListener(
      Events.TOUCH_END,
      this._endCallback as EventListener
    );
    element.removeEventListener(
      Events.TOUCH_DRAG,
      this._dragCallback as EventListener
    );
  };

  _activateDraw = (element: HTMLDivElement) => {
    state.isInteractingWithTool = true;

    element.addEventListener(
      Events.MOUSE_UP,
      this._endCallback as EventListener
    );
    element.addEventListener(
      Events.MOUSE_DRAG,
      this._dragCallback as EventListener
    );
    element.addEventListener(
      Events.MOUSE_MOVE,
      this._dragCallback as EventListener
    );
    element.addEventListener(
      Events.MOUSE_CLICK,
      this._endCallback as EventListener
    );

    element.addEventListener(
      Events.TOUCH_TAP,
      this._endCallback as EventListener
    );
    element.addEventListener(
      Events.TOUCH_END,
      this._endCallback as EventListener
    );
    element.addEventListener(
      Events.TOUCH_DRAG,
      this._dragCallback as EventListener
    );
  };

  _deactivateDraw = (element: HTMLDivElement) => {
    state.isInteractingWithTool = false;

    element.removeEventListener(
      Events.MOUSE_UP,
      this._endCallback as EventListener
    );
    element.removeEventListener(
      Events.MOUSE_DRAG,
      this._dragCallback as EventListener
    );
    element.removeEventListener(
      Events.MOUSE_MOVE,
      this._dragCallback as EventListener
    );
    element.removeEventListener(
      Events.MOUSE_CLICK,
      this._endCallback as EventListener
    );

    element.removeEventListener(
      Events.TOUCH_TAP,
      this._endCallback as EventListener
    );
    element.removeEventListener(
      Events.TOUCH_END,
      this._endCallback as EventListener
    );
    element.removeEventListener(
      Events.TOUCH_DRAG,
      this._dragCallback as EventListener
    );
  };

  /**
   * it is used to draw the length annotation in each
   * request animation frame. It calculates the updated cached statistics if
   * data is invalidated and cache it.
   *
   * @param enabledElement - The Cornerstone's enabledElement.
   * @param svgDrawingHelper - The svgDrawingHelper providing the context for drawing.
   */
  renderAnnotation = (
    enabledElement: Types.IEnabledElement,
    svgDrawingHelper: SVGDrawingHelper
  ): boolean => {
    let renderStatus = false;

    const { viewport } = enabledElement;
    const { element } = viewport;

    let annotations = getAnnotations(this.getToolName(), element);

    // Todo: We don't need this anymore, filtering happens in triggerAnnotationRender
    if (!annotations?.length) {
      return renderStatus;
    }

    annotations = this.filterInteractableAnnotationsForElement(
      element,
      annotations
    );

    if (!annotations?.length) {
      return renderStatus;
    }

    const targetId = this.getTargetId(viewport);
    const renderingEngine = viewport.getRenderingEngine();

    const styleSpecifier: StyleSpecifier = {
      toolGroupId: this.toolGroupId,
      toolName: this.getToolName(),
      viewportId: enabledElement.viewport.id
    };

    // Draw SVG
    for (let i = 0; i < annotations.length; i++) {
      const annotation = annotations[i] as AngleAnnotation;
      const { annotationUID, data } = annotation;
      const { points, activeHandleIndex } = data.handles;

      styleSpecifier.annotationUID = annotationUID;

      const { color, lineWidth, lineDash, angleArcLineDash } =
        this.getAnnotationStyle({
          annotation,
          styleSpecifier
        });

      const canvasCoordinates = points.map((p: Point3) =>
        viewport.worldToCanvas(p)
      );

      // WE HAVE TO CACHE STATS BEFORE FETCHING TEXT
      if (
        !data.cachedStats[targetId!] ||
        data.cachedStats[targetId!].angle == null
      ) {
        data.cachedStats[targetId!] = {
          angle: null
        } as any;

        this._calculateCachedStats(annotation, renderingEngine, enabledElement);
      } else if (annotation.invalidated) {
        this._throttledCalculateCachedStats(
          annotation,
          renderingEngine,
          enabledElement
        );
      }

      let activeHandleCanvasCoords;

      if (
        !isAnnotationLocked(annotation.annotationUID!) &&
        !this.editData &&
        activeHandleIndex !== null
      ) {
        // Not locked or creating and hovering over handle, so render handle.
        activeHandleCanvasCoords = [canvasCoordinates[activeHandleIndex]];
      }

      // If rendering engine has been destroyed while rendering
      if (!viewport.getRenderingEngine()) {
        console.warn("Rendering Engine has been destroyed");
        return renderStatus;
      }

      if (!isAnnotationVisible(annotationUID!)) {
        continue;
      }

      if (canvasCoordinates.length) {
        const handleGroupUID = "0";

        drawHandlesSvg(
          svgDrawingHelper,
          annotationUID!,
          handleGroupUID,
          canvasCoordinates,
          {
            color,
            lineDash,
            lineWidth
          }
        );
      }

      let lineUID = "1";
      drawLineSvg(
        svgDrawingHelper,
        annotationUID!,
        lineUID,
        canvasCoordinates[0],
        canvasCoordinates[1],
        {
          color,
          width: lineWidth,
          lineDash
        }
      );

      renderStatus = true;

      // Don't add textBox until annotation has 3 anchor points (actually 4 because of the center point)
      if (canvasCoordinates.length !== 3) {
        return renderStatus;
      }

      lineUID = "2";

      drawLineSvg(
        svgDrawingHelper,
        annotationUID!,
        lineUID,
        canvasCoordinates[1],
        canvasCoordinates[2],
        {
          color,
          width: lineWidth,
          lineDash
        }
      );

      if (this.configuration.showAngleArc) {
        const center = canvasCoordinates[1];

        // Calculate radius as 1/arcOffset of the minimum distance from center to lines
        const offset = this.configuration.arcOffset; // Default offset is 5 if not provided
        const radius =
          Math.min(
            lineSegment.distanceToPoint(
              [center[0], center[1]],
              [canvasCoordinates[0][0], canvasCoordinates[0][1]],
              [canvasCoordinates[2][0], canvasCoordinates[2][1]]
            ),
            lineSegment.distanceToPoint(
              [center[0], center[1]],
              [canvasCoordinates[2][0], canvasCoordinates[2][1]],
              [canvasCoordinates[0][0], canvasCoordinates[0][1]]
            )
          ) / offset;

        // Calculate start and end angles
        const anglePoints = [];
        let startAngle = Math.atan2(
          canvasCoordinates[0][1] - center[1],
          canvasCoordinates[0][0] - center[0]
        );
        let endAngle = Math.atan2(
          canvasCoordinates[2][1] - center[1],
          canvasCoordinates[2][0] - center[0]
        );

        // Adjust angles if the angle is more than 180 degrees
        if (endAngle < startAngle) {
          endAngle += 2 * Math.PI;
        }
        const angleDifference = endAngle - startAngle;
        if (angleDifference > Math.PI) {
          const temp = startAngle;
          startAngle = endAngle;
          endAngle = temp + 2 * Math.PI;
        }

        // Generate points for the arc
        const segments = 32;
        for (let i = 0; i <= segments; i++) {
          const angle = startAngle + (i / segments) * (endAngle - startAngle);
          anglePoints.push([
            center[0] + radius * Math.cos(angle),
            center[1] + radius * Math.sin(angle)
          ]);
        }

        drawPathSvg(
          svgDrawingHelper,
          annotationUID!,
          "3",
          anglePoints as Point2[],
          {
            color: color as string,
            width: lineWidth as number,
            lineDash: angleArcLineDash as string
          }
        );
      }

      if (!data.cachedStats[targetId!]?.angle) {
        continue;
      }

      const options = this.getLinkedTextBoxStyle(styleSpecifier, annotation);
      if (!options.visibility) {
        data.handles.textBox = {
          hasMoved: false,
          worldPosition: <Types.Point3>[0, 0, 0],
          worldBoundingBox: {
            topLeft: <Types.Point3>[0, 0, 0],
            topRight: <Types.Point3>[0, 0, 0],
            bottomLeft: <Types.Point3>[0, 0, 0],
            bottomRight: <Types.Point3>[0, 0, 0]
          }
        };
        continue;
      }

      const textLines = this.configuration.getTextLines(data, targetId);

      if (!data.handles.textBox.hasMoved) {
        // linked to the vertex by default
        const canvasTextBoxCoords = canvasCoordinates[1];

        data.handles.textBox.worldPosition =
          viewport.canvasToWorld(canvasTextBoxCoords);
      }

      const textBoxPosition = viewport.worldToCanvas(
        data.handles.textBox.worldPosition
      );

      const textBoxUID = "1";
      const boundingBox = drawLinkedTextBoxSvg(
        svgDrawingHelper,
        annotationUID!,
        textBoxUID,
        textLines,
        textBoxPosition,
        canvasCoordinates,
        {},
        options
      );

      const { x: left, y: top, width, height } = boundingBox;

      data.handles.textBox.worldBoundingBox = {
        topLeft: viewport.canvasToWorld([left, top]),
        topRight: viewport.canvasToWorld([left + width, top]),
        bottomLeft: viewport.canvasToWorld([left, top + height]),
        bottomRight: viewport.canvasToWorld([left + width, top + height])
      };
    }

    return renderStatus;
  };

  _calculateCachedStats(
    annotation: Annotation,
    renderingEngine: any,
    enabledElement: IEnabledElement
  ) {
    const data = annotation.data;
    const { element } = enabledElement.viewport;

    // Until we have all three anchors bail out
    if (data.handles!.points!.length !== 3) {
      return;
    }

    const worldPos1 = data.handles!.points![0];
    const worldPos2 = data.handles!.points![1];
    const worldPos3 = data.handles!.points![2];

    const { cachedStats } = data;
    const targetIds = Object.keys(cachedStats!);

    for (let i = 0; i < targetIds.length; i++) {
      const targetId = targetIds[i];
      const angle = angleBetweenLines(
        [worldPos1, worldPos2],
        [worldPos2, worldPos3]
      );
      const { dimensions, imageData } = this.getTargetImageData(targetId);

      // Decide if there's at least one handle is outside of image
      this.isHandleOutsideImage = [worldPos1, worldPos2, worldPos3]
        .map(worldPos =>
          cornerstone.utilities.transformWorldToIndex(imageData, worldPos)
        )
        .some(
          index =>
            !cornerstone.utilities.indexWithinDimensions(index, dimensions)
        );
      cachedStats![targetId] = {
        angle: isNaN(angle) ? "Incomplete Angle" : angle
      };
    }

    const invalidated = annotation.invalidated;
    annotation.invalidated = false;

    // Dispatching annotation modified only if it was invalidated
    if (invalidated) {
      triggerAnnotationModified(annotation, element, ChangeTypes.StatsUpdated);
    }

    return cachedStats;
  }
}

function defaultGetTextLines(
  data: any,
  targetId: string
): string[] | undefined {
  const cachedVolumeStats = data.cachedStats[targetId];
  const { angle } = cachedVolumeStats;

  if (angle === undefined) {
    return;
  }

  if (isNaN(angle)) {
    // The verbiage for incomplete angle is set in cachedStats
    return [`${angle}`];
  }

  const textLines = [
    `${cornerstone.utilities.roundNumber(angle)} ${String.fromCharCode(176)}`
  ];

  return textLines;
}

CustomAngleTool.toolName = "CustomAngle";
export default CustomAngleTool;
