name: Analyze Code Quality and Security

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    
      - name: Debug Sonar token (DEV ONLY)
        run: | 
          echo "Token length: ${#SONAR_TOKEN}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
