name: CI-Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}

      # Setup node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install node modules
      - name: Install node modules
        run: |
          yarn install --frozen-lockfile

      # Generate Build
      - name: Generate build
        run: |
          yarn run build

      # Clean examples and docs file
      - name: Clean examples and docs file
        run: |
          cd ${{ github.workspace }}
          rm -rf docs

      # Publish to npm
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish
